schemaVersion: 2.2.0
components:
  - name: www-gitlab-com
    attributes:
      gl/inject-editor: true
    container:
      image: registry.gitlab.com/gitlab-org/gitlab-build-images:www-gitlab-com-debian-bullseye-ruby-3.0-node-16
      endpoints:
        - name: www
          targetPort: 8000
          secure: true
          protocol: https
